CREATE TABLE buttons
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	mac TEXT UNIQUE NOT NULL,
	label TEXT DEFAULT NULL,
	actions TEXT DEFAULT '[]'
);

CREATE TABLE presses
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ts DATETIME DEFAULT CURRENT_TIMESTAMP,
	button_id INTEGER,
	data TEXT NOT NULL,
	FOREIGN KEY(button_id) REFERENCES buttons(id)
);

CREATE TABLE events
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ts DATETIME DEFAULT CURRENT_TIMESTAMP,
	topic TEXT NOT NULL,
	payload TEXT DEFAULT '{}'
);

CREATE INDEX press_ident
ON presses
(
	JSON_EXTRACT(data, '$.ident')
);
